In [3]:
import torch
import numpy as np
import torchvision
import torch.nn as nn
import pandas as pd
import torch.optim as optim
import torch.functional as F
import torch.utils.data as data
import seaborn as sns
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv("train_data.csv",index_col=0)

In [5]:
data

YearBuilt  Size(sqf)  Floor HallwayType         HeatingType  \
SalePrice                                                                
141592          2006        814      3    terraced  individual_heating   
51327           1985        587      8    corridor  individual_heating   
48672           1985        587      6    corridor  individual_heating   
380530          2006       2056      8    terraced  individual_heating   
78318           1992        644      2       mixed  individual_heating   
...              ...        ...    ...         ...                 ...   
570796          2007       1928     24    terraced  individual_heating   
307079          2015        644     22    terraced  individual_heating   
357522          2007        868     20    terraced  individual_heating   
312389          1978       1327      1    corridor  individual_heating   
393805          2007        868     13    terraced  individual_heating   

                 AptManageType  N_Parkinglot(Ground)  N_Parkinglot(Basement)  \
SalePrice                                                                      
141592     management_in_trust                 111.0                   184.0   
51327          self_management                  80.0                    76.0   
48672          self_management                  80.0                    76.0   
380530     management_in_trust                 249.0                   536.0   
78318          self_management                 142.0                    79.0   
...                        ...                   ...                     ...   
570796     management_in_trust                   0.0                  1270.0   
307079     management_in_trust                 102.0                   400.0   
357522     management_in_trust                   0.0                  1270.0   
312389         self_management                  87.0                     0.0   
393805     management_in_trust                   0.0                  1270.0   

          TimeToBusStop TimeToSubway  N_manager  N_elevators  \
SalePrice                                                      
141592       5min~10min  10min~15min        3.0          0.0   
51327            0~5min   5min~10min        2.0          2.0   
48672            0~5min   5min~10min        2.0          2.0   
380530           0~5min       0-5min        5.0         11.0   
78318        5min~10min  15min~20min        4.0          8.0   
...                 ...          ...        ...          ...   
570796           0~5min       0-5min       14.0         16.0   
307079           0~5min   5min~10min        5.0         10.0   
357522           0~5min       0-5min       14.0         16.0   
312389           0~5min       0-5min        1.0          4.0   
393805           0~5min       0-5min       14.0         16.0   

                   SubwayStation  N_FacilitiesInApt  \
SalePrice                                             
141592     Kyungbuk_uni_hospital                  5   
51327                      Daegu                  3   
48672                      Daegu                  3   
380530                   Sin-nam                  5   
78318                  Myung-duk                  3   
...                          ...                ...   
570796     Kyungbuk_uni_hospital                 10   
307079                     Daegu                  7   
357522     Kyungbuk_uni_hospital                 10   
312389     Kyungbuk_uni_hospital                  3   
393805     Kyungbuk_uni_hospital                 10   

           N_FacilitiesNearBy(Total)  N_SchoolNearBy(Total)  
SalePrice                                                    
141592                           6.0                    9.0  
51327                           12.0                    4.0  
48672                           12.0                    4.0  
380530                           3.0                    7.0  
78318                            9.0                   14.0  
...                     

In [10]:
# Wypisanie wartości kolumn nienumerycznych w celu ich znormalizowania

print(data["HeatingType"].unique())
print(data["AptManageType"].unique())
print(data["HallwayType"].unique())
print(data["TimeToBusStop"].unique())
print(data["SubwayStation"].unique())

['individual_heating' 'central_heating']
['management_in_trust' 'self_management']
['terraced' 'corridor' 'mixed']
['5min~10min' '0~5min' '10min~15min']
['Kyungbuk_uni_hospital' 'Daegu' 'Sin-nam' 'Myung-duk' 'Chil-sung-market'
 'Bangoge' 'Banwoldang' 'no_subway_nearby']


In [13]:
data.loc[ data["HeatingType"] == "individual_heating", "HeatingType"] = 1.0
data.loc[ data["HeatingType"] == "central_heating", "HeatingType"] = 0.0
print(data["HeatingType"].unique())

[1.0 0.0]


In [14]:
i = 0.0
for d in data['AptManageType'].unique():
    data.loc[data["AptManageType"] == d, "AptManageType"] = i
    i = i + 1
print(data["AptManageType"].unique())

[0.0 1.0]


In [15]:
i = 0.0
dataType = "HallwayType"
for d in data[dataType].unique():
    data.loc[data[dataType] == d, dataType] = i
    i = i + 1
print(data[dataType].unique())

[0.0 1.0 2.0]


In [16]:
i = 0.0
dataType = "TimeToBusStop"
for d in data[dataType].unique():
    data.loc[data[dataType] == d, dataType] = i
    i = i + 1
print(data[dataType].unique())

[0.0 1.0 2.0]


In [17]:
i = 0.0
dataType = "SubwayStation"
for d in data[dataType].unique():
    data.loc[data[dataType] == d, dataType] = i
    i = i + 1
print(data[dataType].unique())

[0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0]
